# Generated by Django 3.1.5 on 2021-01-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_updated_timestamp', models.DateTimeField(auto_now=True, db_index=True)),
                ('has_been_contacted', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=80)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
