# Generated by Django 3.1.5 on 2021-01-20 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210120_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='uuid',
            new_name='id',
        ),
    ]
